site_name: dpvis Documentation
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.sections
    - navigation.path
    - navigation.top
nav:
  - Home: README.md
  - Getting Started: getting_started.md
  - Examples:
    - examples/fibonacci.md
    - examples/knapsack.md
    - examples/matrix_traversal.md
    - examples/excavation.md
  - API:
    - dp_array.md
    - logger.md
    - visualizer.md
plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py 
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              returns_named_value: False
markdown_extensions:
  - pymdownx.highlight:
      # anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  - attr_list
watch:
- dp
- demos
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
