site_name: dpvis Documentation
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.sections
    - navigation.path
    - navigation.top
nav:
  - Home: README.md
  - Getting Started: getting_started.md
  - API:
    - dp_array.md
    - logger.md
    - visualizer.md
plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py 
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              returns_named_value: False
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
watch:
- dp
