site_name: My Docs
theme:
  name: material
  features:
    - navigation.sections
nav:
  - Home: index.md
  - API:
    - dp_array.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              returns_named_value: False
