site_name: dpvis Documentation
repo_url: https://github.com/itsdawei/dpvis
edit_uri: edit/main/docs/
repo_name: dpvis
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: green
      accent: red

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: red

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: green
      accent: red
  features:
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - navigation.top
  icon:
    repo: fontawesome/brands/github
nav:
  - Home: README.md
  - Getting Started: getting_started.md
  - Test Mode Tutorial: test_mode/test_mode.md
  - Examples:
      - examples/index.md
      - Fibonacci: examples/fibonacci.md
      - Knapsack: examples/knapsack.md
      - Weighted Interval Scheduling: examples/wis.ipynb
      - Edit Distance: examples/edit_distance.md
  - API:
      - DPArray: api/dp_array.md
      - Logger: api/logger.md
      - Visualizer: api/visualizer.md
plugins:
  - mkdocs-jupyter:
      ignore: [".ipynb_checkpoints/*.ipynb"]
      remove_tag_config:
        remove_all_outputs_tags:
          - hide_output
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              returns_named_value: false
  - git-revision-date-localized
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      # anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  - attr_list
watch:
  - dp
  - demos
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
