name: Deploy Live Demos on Main


on:
  push:
    branches: [main]
    # branches: [main]
    paths:
      - 'demo/**'
      - 'Dockerfile'
      - 'Makefile'

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: dpvis-demo
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Auth Docker to Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Detect changed demos and deploy
      run: |
        # List of allowed demos
        ALLOWED=(wis)

        # Find changed demo scripts (must match demo/*.py)
        CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^demo/[^/]+\.py$' || true)

        echo "Changed files:"
        echo "$CHANGED"

        # Extract demo names (strip path + .py)
        MATCHED=()
        for file in $CHANGED; do
          name=$(basename "$file" .py)
          if [[ " ${ALLOWED[*]} " =~ " $name " ]]; then
            MATCHED+=("$name")
          fi
        done

        if [ ${#MATCHED[@]} -eq 0 ]; then
          echo "No deployable demos changed. Skipping deployment."
          exit 0
        fi

        echo "Deploying changed demos: ${MATCHED[*]}"
        make "${MATCHED[*]}"
