name: Docs

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1.3.4
      - name: Install library
        run: poetry install --no-interaction --with docs
      - name: Build docs
        run: poetry run make docs
