name: Docs

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.8"
      - name: Install deps
        run: pip install .[dev]
      - name: Build docs
        run: make docs
