name: Preview Deploy a Demo

on:
  workflow_dispatch:
    inputs:
      demo:
        description: "Demo name (e.g. wis)"
        required: true
      suffix:
        description: "Optional suffix (e.g. preview)"
        required: false
        default: "preview"

env:
  PROJECT_ID: dpvis-demo
  REGION: us-central1
  REPO: us-central1-docker.pkg.dev/dpvis-demo/dpvis-repo

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Authenticate Docker with Artifact Registry
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build, Push, and Deploy to Cloud Run
      run: |
        DEMO="${{ github.event.inputs.demo }}"
        SUFFIX="${{ github.event.inputs.suffix }}"
        DEPLOY_AS="$DEMO"
        if [[ "$SUFFIX" != "" ]]; then
          DEPLOY_AS="${DEMO}-${SUFFIX}"
        fi

        IMAGE="${{ env.REPO }}/$DEPLOY_AS"

        echo "🔨 Building $DEMO → $IMAGE"
        docker build -t "$IMAGE" --build-arg DEMO="$DEMO" .

        echo "📤 Pushing image to Artifact Registry"
        docker push "$IMAGE"

        echo "🚀 Deploying to Cloud Run: $DEPLOY_AS"
        gcloud run deploy "$DEPLOY_AS" \
          --image "$IMAGE" \
          --region "${{ env.REGION }}" \
          --platform managed \
          --allow-unauthenticated

    - name: Show deployed service URL
      run: |
        URL=$(gcloud run services describe "$DEPLOY_AS" \
          --region "${{ env.REGION }}" \
          --platform managed \
          --format="value(status.url)")
        echo "✅ Service URL: $URL"
