name: Tests

on: [push]

defaults:
  run:
    # The default shell must be set like this so that bash will source the
    # profile, which contains settings initialized by Conda:
    # https://github.com/marketplace/actions/setup-miniconda#important
    shell: bash -el {0}

jobs:
  test:
    strategy:
      max-parallel: 12 # All in parallel.
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.8"] # There is a limit for private repos
        exclude:
          # To cut down on runtime since Mac seems to take the longest.
          - os: macos-latest
            python-version: "3.9"
          - os: macos-latest
            python-version: "3.10"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1.3.4
      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}
      - name: Install library
        run: poetry install --no-interaction
      - name: pytest
        run: pytest tests
