name: Tests

on: [push]

defaults:
  run:
    # The default shell must be set like this so that bash will source the
    # profile, which contains settings initialized by Conda:
    # https://github.com/marketplace/actions/setup-miniconda#important
    shell: bash -el {0}

jobs:
  test:
    strategy:
      max-parallel: 12 # All in parallel.
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        exclude:
          # To cut down on runtime since Mac seems to take the longest.
          - os: macos-latest
            python-version: "3.9"
          - os: macos-latest
            python-version: "3.10"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependecies
        run: poetry install --no-interaction --no-root
      - name: Install our library
        run: poetry install --no-interaction
      - name: pytest
        run: poetry run make test
